
version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 3636
      MYSQL_DATABASE: app_db
      MYSQL_USER: gian
      MYSQL_PASSWORD: 3636
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  contabil-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      USERDB: app_db
      PORT: 3000
    volumes:
      - ./upload:/app/upload
      - /app/node_modules
      - .:/app
volumes:
  dbdata:
